<?php

namespace app\admin\controller;

use app\common\model\AppRoll;
use app\common\model\Announcement as Goods;
use app\common\model\Order;
use app\common\model\User;
use think\facade\View;

class Notice extends Base
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $product_type = config('user.product_type'); //后台编辑产品类型 1 酒店 2 餐厅
        View::assign(['product_type' => $product_type]);
    }

    //产品列表
    public function list()
    {
        if ($this->request->isAjax()) {
            $price_min = $this->request->post('price_min', 0, 'intval');
            $price_max = $this->request->post('price_max', 0, 'intval');
            $page = $this->request->post('page', 1, 'intval');
            $list = (new Goods)->order('price asc')->page($page, $this->pageSize)->select()->toArray();
            if (!$list)
                $this->result(202, '到底了');
            else {
                if (count($list) < $this->pageSize) {
                    $this->result(201, '获取成功', $list);
                } else {
                    $this->result(200, '获取成功', $list);
                }
            }
        }
        $name = $this->request->get('name', '', 'trim');
        $start_time = $this->request->get('start_time', '', 'trim');
        $where = [];
        if ($name)
            $where[] = ['title', 'like', "%$name%"];
        if ($start_time)
            $where[] = ['update_time', '>', strtotime($start_time)];
        $list = Goods::where($where)->paginate($this->pageSize);
        View::assign(['list' => $list, 'name' => $name, 'start_time' => $start_time]);
        return View::fetch();
    }

    //产品添加
    public function add()
    {
        if ($this->request->isAjax()) {
            $data = $this->request->post();
            $id = $data['id'] ?? 0;
            unset($data['id']);
            if ($id)
                $res = Goods::update($data, ['id' => $id]);
            else
                $res = Goods::create($data);
            if ($res)
                $this->result(200, '操作成功');
            else
                $this->result(500, '操作失败');
        }
        $id = $this->request->get('id', 0);
        $info = [];
        if ($id) {
            $info = Goods::find($id);
           
        }
        View::assign(['info' => $info, 'id' => $id]);
        return View::fetch();
    }

    //产品删除
    public function del()
    {
        $id = $this->request->post('id', 0, 'intval');
        if (!$id)
            $this->result(404, '参数有误');
        $res = Goods::destroy($id);
        if ($res)
            $this->result(200, '删除成功');
        else
            $this->result(500, '删除失败');
    }

   

  

}
